### ISSUE TITLE
IMSI-catcher

### ISSUE THREAD

**Issue by JamesSmi-ux** [TheRipperJhon/IMSI_Catcher#2]
Does anyone  knows about this error? 

I'm running grgsm_livemon and wireshark in the same time.

root@kali:~/Desktop/IMSI-catcher-master# python simple_IMSI-catcher.py
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId ; Timestamp
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 553, in <module>
    udpserver(port=options.port, prn=find_imsi)
  File "simple_IMSI-catcher.py", line 502, in udpserver
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by JamesSmi-ux** [comment]
when I stop grgsm_livemon in terminal 2 and run the command in terminal 1 with python simple_IMSI-catcher.py --sniff is giving me this: 

root@kali:~/Desktop/IMSI-catcher-master# python simple_IMSI-catcher.py --sniff
Traceback (most recent call last):
  File "simple_IMSI-catcher.py", line 548, in <module>
    from scapy.all import sniff, UDP
ImportError: No module named scapy.all

:-??
without --sniff 
root@kali:~/Desktop/IMSI-catcher-master# python simple_IMSI-catcher.py
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId ; Timestamp

nothing..

Does anyone knows what I need to do ? 

Thank you

**Comment by JamesSmi-ux** [comment]
I have only rtl-sdr device , no hackrf..
